version: '2'

services:
  wordpress:
    container_name: "${project}_wordpress"
    image: wordpress:5.3-php7.2
    ports:
      - 8080:80
    volumes:
      - ../dist:/var/www/html/wp-content/plugins/podlove-web-player-beta
      - ../uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_PASSWORD: "${database_password}"
    depends_on:
      - mysql

  mysql:
    container_name: "${project}_database"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${database_password}"
    volumes:
      - ../config/database:/etc/mysql/conf.d
      - ../database.sql:/docker-entrypoint-initdb.d/dump.sql
