version: '3.3'

services:
  wordpress:
    container_name: "${project}_wordpress"
    image: wordpress:5.4-php7.2
    ports:
      - 8080:80
    volumes:
      - ../wp:/var/www/html/
      - ../dist:/var/www/html/wp-content/plugins/podlove-web-player
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_PASSWORD: "${database_password}"
    depends_on:
      - mysql

  mysql:
    container_name: "${project}_database"
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: "${database_password}"
    volumes:
      - ../database:/docker-entrypoint-initdb.d
