name: Qualify Branch
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build
      run: |
        npm ci
        npm run build
