name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.11.0
        with:
          enable-cache: true
      - name: install
        run: devbox run npm ci
      - name: build
        run: |
          devbox run npm run build
          devbox run npm run publish:prepare
          devbox run npm run publish:workspace
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: podlove-web-player
